### PR TITLE
Create S25FL128L.toml

### PR DESCRIPTION
**Pull request by DJDevon3**
add Cypress 16MB flash chip

### CODE REVIEW

**Comment by dhalbert** [comment]
hw testing is in progress...

**Comment by DJDevon3** [comment]
hw test a failure with no possibility of success, at least not on an nrf52840 bluefruit feather sense that i was going for. got the wrong chip package. needed uson8, got an soic8. 

is there a quick way of finding a board that i might be able to use the soic8 so it doesn't go to waste other than going through every adafruit product page or board spec sheet? a list of boards that use an soic8 chip?

how to rescind a PR? delete on your end or mine?

**Comment by tannewt** [comment]
> is there a quick way of finding a board that i might be able to use the soic8 so it doesn't go to waste other than going through every adafruit product page or board spec sheet? a list of boards that use an soic8 chip?

Not that I know of. I believe the older boards use soic8. The QT PY M0 has an empty spot and the Feather M0 has one populated. (M0 isn't that great for CP though.) Looks like Metro M4 has SOIC-8 as well.

I think either of us can "close" the PR. I'll let you do it if you don't want to test on other hardware.

**Comment by DJDevon3** [comment]
@dhalbert Is there a way to set this PR on hold? I've revisited it and had some small adapter PCB's made. Might make this one happen this week with luck. HW test should happen tomorrow. Hot plate, smd paste, and reflow setup arrived. :)

**Comment by ladyada** [comment]
yep click 'convert to draft'

**Comment by tannewt** [comment]
@DJDevon3 Still working on this?

**Comment by DJDevon3** [comment]
@tannewt Yes I put this on the back burner for long enough. Couldn't figure out how to "convert to draft". I looked it up and there's no PR in my toml repo to convert to draft... 

Ended up designing a little adapter board, had it fabricated, and is sitting on my desk waiting for me to complete the custom UF2.

I lost the custom UF2 so will have to remake it. That also means reinstalling WSL Ubuntu. I ripped it out because someone originally said a problem with the S2 hard reset bug was only on my PC... turned out to be far from the truth. I literally ripped out a 10 port USB hub and anything that wasn't nailed down in the OS tracking down that bug. There were many things that lead to this point.

I'll get back on it. I do want to do it just because I think the idea of a 16MB bluefruit sense is cool.

**Comment by tannewt** [comment]
The convert to draft option is under the reviewers section of the PR page on the right hand side. (I had to look it up.)

**Comment by DJDevon3** [comment]
@tannewt I've never done a review and don't think I can review my own PR so I never see that.  Keeping this one open anyway. Got WSL Ubuntu, git, mpy-cross, etc.. installed yesterday and confirmed it will create a good UF2 build. Making this project my focus this week, I'm on it. 👍

**Comment by DJDevon3** [comment]
Now that the W25Q128JVSSIQ 16MB flash chips are not only available again but Adafruit is now carrying them directly [W25Q128JVSSIQ](https://www.adafruit.com/product/5634) I've decided to go with their existing board definition and chip. Closing.

**Pull request closed without merging**
